exports.branchServiceError = {
    BRANCH_ERR_ADDRESS_ALREADY_IN_USE: "errors.address_already_in_user",
    BRANCH_ERR_BRANCH_NOT_FOUND: "errors.branch_not_found",
}
